name: 自动发行
on:
  push:
    tags:
    - 'v*'

jobs: 
  build:
    name: 发行资产
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v2
      - name: 打包云函数
        run: |
          sed -i s/PLATFORM\=./PLATFORM\=2/g graph_api_app.sh
          zip -r tencent_cloud_auto_api_call.zip ./ -x ".git/*" -x ".github/*"
      - name: 构建发行版
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.repository }} ${{ github.ref }}
          draft: false
          prerelease: false
      - name: 上传资产
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./tencent_cloud_auto_api_call.zip
          asset_name: tencent_cloud_auto_api_call.zip
          asset_content_type: application/zip