name: 部署到腾讯云函数
on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    - name: 迁出环境变量
      env:
        TC_SECRET_ID: ${{secrets.TC_SECRET_ID}}
        TC_SECRET_KEY: ${{secrets.TC_SECRET_KEY}}
        CLIENT_ID1: ${{secrets.CLIENT_ID1}}
        CLIENT_ID2: ${{secrets.CLIENT_ID2}}
        CLIENT_SECRET1: ${{secrets.CLIENT_SECRET1}}
        CLIENT_SECRET2: ${{secrets.CLIENT_SECRET2}}
    steps:
      - name: 迁出代码
        uses: actions/checkout@v2
      - name: 更改参数
        run: |
          sed -i s/PLATFORM\=./PLATFORM\=2/g graph_api_app.sh
      - name: 部署到腾讯云函数
        uses: TencentCloudBase/cloudbase-action@v2
        with:
          secretId: ${{secrets.TC_SECRET_ID}}
          secretKey: ${{secrets.TC_SECRET_KEY}}
          envId: ${{secrets.TC_ENVID}}
